### ISSUE TITLE
有効化時にエラー（EC-CUBE3.0.3, 3.0.4のみ再現）

### ISSUE THREAD

**Issue by hiroaki-zeniya** [EC-CUBE/Recommend-plugin#1]
EC-CUBE3.0.3, 3.0.4にて、インストール後、有効化のタイミングで下記エラーが発生。

▼エラーログ
"myapp.CRITICAL: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO dtb_block (block_id, block_name, file_name, create_date, update_date, logic_flg, deletable_flg, device_type_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [13, ""\u304a\u3059\u3059\u3081\u5546\u54c1"", ""recommend_product_block"", ""2015-12-24 11:45:19"", ""2015-12-24 11:45:19"", 1, 0, 10]:  SQLSTATE[23505]: Unique violation: 7 ERROR:  重複キーが一意性制約""device_type_id""に違反しています DETAIL:  キー (device_type_id, file_name)=(10, recommend_product_block) はすでに存在します (uncaught exception) at /home/web/check.ec-cube.net/html/plugin/kaji/eccube-3.0.4-pgsql/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 63 {""exception"":""[object](Doctrine\DBAL\Exception\UniqueConstraintViolationException%28code: 0%29: An exception occurred while executing 'INSERT INTO dtb_block %28block_id, block_name, file_name, create_date, update_date, logic_flg, deletable_flg, device_type_id%29 VALUES %28?, ?, ?, ?, ?, ?, ?, ?%29' with params [13, ""\u304a\u3059\u3059\u3081\u5546\u54c1"", ""recommend_product_block"", ""2015-12-24 11:45:19"", ""2015-12-24 11:45:19"", 1, 0, 10]:nnSQLSTATE[23505]: Unique violation: 7 ERROR:  重複キーが一意性制約""device_type_id""に違反していますnDETAIL:  キー %28device_type_id, file_name)=(10, recommend_product_block) はすでに存在します at /home/web/check.ec-cube.net/html/plugin/kaji/eccube-3.0.4-pgsql/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:63, Doctrine\DBAL\Driver\PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  重複キーが一意性制約\""device_type_id\""に違反しています\nDETAIL:  キー (device_type_id, file_name)=(10, recommend_product_block) はすでに存在します at /home/web/check.ec-cube.net/html/plugin/kaji/eccube-3.0.4-pgsql/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  重複キーが一意性制約\""device_type_id\""に違反し>
ています\nDETAIL:  キー (device_type_id, file_name)=(10, recommend_product_block) はすでに存在します at /home/web/check.ec-cube.net/html/plugin/kaji/eccube-3.0.
4-pgsql/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)""} []"

**Comment by ryo-endo** [comment]
対象動作環境は3.0.5以上となっておりますので、CLOSEします。
